### ISSUE TITLE
boomer work with locust some error report

### ISSUE THREAD

**Issue by KnightBlood** [myzhan/boomer#153]
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Web\loadtest\locust\venv\Scripts\locust.exe\__main__.py", line 7, in <module>
  File "e:\web\loadtest\locust\venv\lib\site-packages\locust\main.py", line 483, in main
    shutdown()
  File "e:\web\loadtest\locust\venv\lib\site-packages\locust\main.py", line 456, in shutdown
    print_stats(runner.stats, current=False)
  File "e:\web\loadtest\locust\venv\lib\site-packages\locust\stats.py", line 731, in print_stats
    console_logger.info(r.to_string(current=current))
  File "e:\web\loadtest\locust\venv\lib\site-packages\locust\stats.py", line 533, in to_string
    self.median_response_time or 0,
  File "e:\web\loadtest\locust\venv\lib\site-packages\locust\stats.py", line 369, in median_response_time
    if median > self.max_response_time:
TypeError: '>' not supported between instances of 'str' and 'float'

locust:2.5.1

from locust import User, TaskSet, task

class MyTaskSet(TaskSet):
    @task(20)
    def hello(self):
        pass

class Dummy(User):
    task_create = MyTaskSet

boomer:lasteest

script your readme demo

**Comment by myzhan** [comment]
It's a bug introduced recently, please update boomer and try again.
