### ISSUE TITLE
after set users and hatch rate， app crashed

### ISSUE THREAD

**Issue by jetgeng** [myzhan/boomer#18]
i have 13 slave， and when i set user to 1300 and hatch rate to 20， them my  app which boomer crashed 。 give me some information as below： 
```
2017/12/18 17:19:41 runner.go:56: Hatching and swarming 12 clients at the rate 0 clients/s...
panic: runtime error: integer divide by zero

goroutine 22 [running]:
github.com/myzhan/boomer.(*runner).spawnGoRoutines(0xc42012f6e0, 0xc, 0xc42013c120)
        /Users/jet/GoPath/src/github.com/myzhan/boomer/runner.go:73 +0x646
github.com/myzhan/boomer.(*runner).startHatching(0xc42012f6e0, 0xc, 0x0)
        /Users/jet/GoPath/src/github.com/myzhan/boomer/runner.go:122 +0x13f
github.com/myzhan/boomer.(*runner).getReady.func1(0xc42012f6e0)
        /Users/jet/GoPath/src/github.com/myzhan/boomer/runner.go:169 +0x2c2
created by github.com/myzhan/boomer.(*runner).getReady
        /Users/jet/GoPath/src/github.com/myzhan/boomer/runner.go:179 +0x68
[jet@localhost perforceTest]$ ./transfer-benchmark_linux_amd64    --master-host=127.0.0.1 --master-port=5557  --rpc=zeromq
```

**Comment by myzhan** [comment]
I can't reproduce this problem, because locust doesn't send message to boomer that hatch rate is zero. Which version of locust did you used?

![image](https://user-images.githubusercontent.com/953781/34103816-1e7832a4-e429-11e7-979c-95fe898709da.png)
