### ISSUE TITLE
goroutine exception

### ISSUE THREAD

**Issue by aidylewis** [myzhan/boomer#22]
Ubuntu 16.04
go1.10 linux/amd64

Running this server:
```go
package main

import (
	"log"
	"net/http"
	"sync/atomic"
	"time"
)

func main() {
	count := uint64(0)
	tick := time.NewTicker(time.Second)
	http.ListenAndServe(":6060", http.HandlerFunc(
		func(w http.ResponseWriter, r *http.Request) {
			atomic.AddUint64(&count, 1)
			select {
			case <-tick.C:
				log.Printf("Rate: %d", atomic.SwapUint64(&count, 0))
			default:
			}
		},
	))
}
```
With this test:
```go
package main

import (
	"fmt"
	"github.com/myzhan/boomer"
	"net/http"
)

func urlBash() {
	start := boomer.Now()

	localServer := "http://localhost:6060"
	resp, _ := http.Get(localServer)

	elapsed := boomer.Now() - start

	var result string
	if resp.StatusCode == 200 {
		result = "request_success"
	} else {
		result = "request_failure"
	}

	boomer.Events.Publish(result, "http", "urlBash", elapsed, int64(10))

}

func main() {

	task := &boomer.Task{
		Name: "urlBash",
		Fn:   urlBash,
	}

	boomer.Run(task)
}
```
Exception
```
goroutine 50 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/lib/go-1.6/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
        /usr/lib/go-1.6/src/runtime/debug/stack.go:16 +0x18
github.com/myzhan/boomer.(*runner).safeRun.func1()
        /home/ubuntu/go/src/github.com/myzhan/boomer/runner.go:47 +0x53
panic(0x9b10e0, 0xc82000e0d0)
        /usr/lib/go-1.6/src/runtime/panic.go:443 +0x4e9
main.urlBash()
        /home/ubuntu/go/src/github.com/bbc/locust-load-tests/examples/urlbash/main.go:17 +0x75
github.com/myzhan/boomer.(*runner).safeRun(0xc820142120, 0xba2300)
        /home/ubuntu/go/src/github.com/myzhan/boomer/runner.go:51 +0x3a
github.com/myzhan/boomer.(*runner).spawnGoRoutines.func1(0xc820190060, 0xc820142120, 0xba2300)
        /home/ubuntu/go/src/github.com/myzhan/boomer/runner.go:91 +0xd5
created by github.com/myzhan/boomer.(*runner).spawnGoRoutines
        /home/ubuntu/go/src/github.com/myzhan/boomer/runner.go:95 +0x497
```

**Comment by myzhan** [comment]
The fifth param of request_failure is a string. Take a look at locust’s failure tab.

If you are writing tests for a HTTP server, http_benchmark.go in examples folder may help.

**Comment by aidylewis** [comment]
Misread your post. I will check this again tomorrow.
