### ISSUE TITLE
停止 locust master 的时候，出现 panic

### ISSUE THREAD

**Issue by yuyongID** [myzhan/boomer#49]
locust master 停止的时候出现了个 panic，大佬来处理一下吗？

```
16:14:15 client_gomq.go:72: runtime error: index out of range
goroutine 67 [running]:
runtime/debug.Stack(0xc000084000, 0x2, 0xc00021e0c0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/myzhan/boomer.(*gomqSocketClient).recv.func1()
        /Users/yuongID/go/pkg/mod/github.com/myzhan/boomer@v0.0.0-20181224091118-43803d597cce/client_gomq.go:73 +0x94
panic(0x98d220, 0xeb98d0)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/zeromq/gomq.(*Socket).Recv(...)
        /Users/yuongID/go/pkg/mod/github.com/zeromq/gomq@v0.0.0-20181008000130-95dc37dee5c4/socket.go:115
github.com/myzhan/boomer.(*gomqSocketClient).recv(0xc0001ac0a0)
        /Users/yuongID/go/pkg/mod/github.com/myzhan/boomer@v0.0.0-20181224091118-43803d597cce/client_gomq.go:79 +0x1b2
created by github.com/myzhan/boomer.(*gomqSocketClient).connect
        /Users/yuongID/go/pkg/mod/github.com/myzhan/boomer@v0.0.0-20181224091118-43803d597cce/client_gomq.go:55 +0x6ad
16:14:15 client_gomq.go:74: The underlying socket connected to master(172.16.16.72:5558) may be broken, please restart both locust and boomer
```

**Comment by myzhan** [comment]
这个是 gomq 内部抛出来的 panic，目前无法处理，我已经捕获并打印了日志，建议重启 master 和 slave。

在 master 和 slave 之间网络不好的时候容易出现。

**Comment by yuyongID** [comment]
> 这个是 gomq 内部抛出来的 panic，目前无法处理，我已经捕获并打印了日志，建议重启 master 和 slave。
> 
> 在 master 和 slave 之间网络不好的时候容易出现。

无法重新连接到重启后的 locust master 吗？slave 这个时候 panic退出，不能短线重连，如果 slave 数量多的话，其实操作起来很难受的。

**Comment by myzhan** [comment]
这个我有空看看，目前传输层全部交给 gomq，包括重连，locust 和 boomer 都假设这个连接不会断。

如果目前影响使用，可以切换到 goczmq，看看 README 中的方法。

**Comment by myzhan** [comment]
See also https://github.com/zeromq/gomq/issues/75

**Comment by yuyongID** [comment]
> 这个我有空看看，目前传输层全部交给 gomq，包括重连，locust 和 boomer 都假设这个连接不会断。
> 
> 如果目前影响使用，可以切换到 goczmq，看看 README 中的方法。

感觉这个地方是需要处理一下，如果是公网测试的话，网络波动会出现 slave 频繁 panic。
