### ISSUE TITLE
unkown panic

### ISSUE THREAD

**Issue by myzhan** [myzhan/boomer#5]
2016/08/11 14:29:01 Hatching and swarming 1000 clients at the rate 1000 clients/s...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4623d8]

goroutine 22 [running]:
panic(0x9a00e0, 0xc820010120)
    /home/zhanqp/local/go/src/runtime/panic.go:481 +0x3e6
github.com/myzhan/boomer.(*StatsEntry).log(0x0, 0x408b7a432d4a44dd, 0xa)
    /home/zhanqp/src/gowork/src/github.com/myzhan/boomer/stats.go:78 +0x18
github.com/myzhan/boomer.init.2.func1()
    /home/zhanqp/src/gowork/src/github.com/myzhan/boomer/stats.go:255 +0x103
created by github.com/myzhan/boomer.init.2
    /home/zhanqp/src/gowork/src/github.com/myzhan/boomer/stats.go:262 +0x111
exit status 2

**Comment by myzhan** [comment]
It's a race condition.

fixed: https://github.com/myzhan/boomer/commit/c6da7f95d6b7cec26b2299429c5fc740e3c81146
