### ISSUE TITLE
配合新版的lucust使用时出现问题

### ISSUE THREAD

**Issue by NeilWai** [myzhan/boomer#70]
```
[2019-11-11 16:45:17,691] hostxx/INFO/locust.main: Starting web monitor at *:8089
[2019-11-11 16:45:17,692] hostxx/INFO/locust.main: Starting Locust 0.12.2
[2019-11-11 16:45:36,700] hostxx/INFO/locust.runners: Client u'hostxx_97d7292e045c46d7b06772af15af3339' reported as ready. Currently 1 clients ready to swarm.
[2019-11-11 16:45:54,338] hostxx/INFO/locust.runners: Sending hatch jobs to 1 ready clients
[2019-11-11 16:45:54,701] hostxx/ERROR/stderr: Traceback (most recent call last):
[2019-11-11 16:45:54,701] hostxx/ERROR/stderr: File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
[2019-11-11 16:45:54,701] hostxx/ERROR/stderr: File "/usr/lib/python2.7/site-packages/locust/runners.py", line 387, in client_listener
[2019-11-11 16:45:54,701] hostxx/ERROR/stderr: events.slave_report.fire(client_id=msg.node_id, data=msg.data)
[2019-11-11 16:45:54,702] hostxx/ERROR/stderr: File "/usr/lib/python2.7/site-packages/locust/events.py", line 34, in fire
[2019-11-11 16:45:54,702] hostxx/ERROR/stderr: handler(**kwargs)
[2019-11-11 16:45:54,702] hostxx/ERROR/stderr: File "/usr/lib/python2.7/site-packages/locust/stats.py", line 616, in on_slave_report
[2019-11-11 16:45:54,702] hostxx/ERROR/stderr: global_stats.total.extend(StatsEntry.unserialize(data["stats_total"]))
[2019-11-11 16:45:54,702] hostxx/ERROR/stderr: File "/usr/lib/python2.7/site-packages/locust/stats.py", line 405, in unserialize
[2019-11-11 16:45:54,702] hostxx/ERROR/stderr: setattr(obj, key, data[key])
[2019-11-11 16:45:54,702] hostxx/ERROR/stderr: KeyError: 'num_none_requests'
[2019-11-11 16:45:54,702] hostxx/ERROR/stderr: 2019-11-11T08:45:54Z
```
代码是取boomer最新的，安装的是Locust 0.12.2。
测试脚本是 examples/http/client.go, 请问这如何解决？谢谢。

**Comment by myzhan** [comment]
这个 commit 里面解决了 https://github.com/myzhan/boomer/commit/dd790dc0866100b0cfdb480b2e1e9d42017dae99

可以再更新一下
