### ISSUE TITLE
0.14.5 -> KeyError: 'current_cpu_usage'

### ISSUE THREAD

**Issue by seon1-kim** [myzhan/boomer#81]
**Describe the bug**
boomer not working with locust 0.14.5. 
I want check cpu usage but is not working. 
Currently, I use locust 0.13

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: ubuntu 18.04
 - Go Version: 1.13

**Additional context**
logs
```
[2020-03-05 03:17:18,568] /INFO/locust.main: Starting web monitor at http://*:80
[2020-03-05 03:17:18,568] /INFO/locust.main: Starting Locust 0.14.5
[2020-03-05 03:17:21,714] /INFO/locust.runners: Client '_bd3b6e34238a452691a6b9db473b764a' reported as ready. Currently 1 clients ready to swarm.
[2020-03-05 03:17:22,715] /ERROR/stderr: Traceback (most recent call last):
[2020-03-05 03:17:22,715] /ERROR/stderr:
[2020-03-05 03:17:22,715] /ERROR/stderr: File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
[2020-03-05 03:17:22,715] /ERROR/stderr:
[2020-03-05 03:17:22,715] /ERROR/stderr: File "/home/ubuntu/.local/lib/python3.6/site-packages/locust/runners.py", line 459, in client_listener
    c.cpu_usage = msg.data['current_cpu_usage']
[2020-03-05 03:17:22,715] /ERROR/stderr:
[2020-03-05 03:17:22,715] /ERROR/stderr: KeyError: 'current_cpu_usage'
[2020-03-05 03:17:22,715] /ERROR/stderr:
[2020-03-05 03:17:22,715] /ERROR/stderr: 2020-03-05T03:17:22Z
[2020-03-05 03:17:22,715] /ERROR/stderr:
[2020-03-05 03:17:22,715] /ERROR/stderr: <Greenlet at 0x7f857f1aed48: <bound method MasterLocustRunner.client_listener of <locust.runners.MasterLocustRunner object at 0x7f857f0659e8>>> failed with KeyError
[2020-03-05 03:17:27,572] /INFO/locust.runners: Slave _bd3b6e34238a452691a6b9db473b764a failed to send heartbeat, setting state to missing.
[2020-03-05 03:17:33,320] /WARNING/locust.runners: You are running in distributed mode but have no slave servers connected. Please connect slaves prior to swarming.
```

**Comment by myzhan** [comment]
It has been fixed already, try to update boomer.
