### ISSUE TITLE
Locust 1.0.3 运行出错

### ISSUE THREAD

**Issue by Neyzoter** [myzhan/boomer#87]
**问题描述**

Locust 1.0.3 运行prometheus_exporter.py出错。

```bash
> locust --master -f prometheus_exporter.py
```

结果

```
Traceback (most recent call last):
  File "/home/scc/software/Anaconda/anaconda3/bin/locust", line 11, in <module>
    load_entry_point('locust==1.0.3', 'console_scripts', 'locust')()
  File "/home/scc/software/Anaconda/anaconda3/lib/python3.7/site-packages/locust-1.0.3-py3.7.egg/locust/main.py", line 113, in main
    docstring, user_classes = load_locustfile(locustfile)
  File "/home/scc/software/Anaconda/anaconda3/lib/python3.7/site-packages/locust-1.0.3-py3.7.egg/locust/main.py", line 77, in load_locustfile
    imported = __import_locustfile__(locustfile, path)
  File "/home/scc/software/Anaconda/anaconda3/lib/python3.7/site-packages/locust-1.0.3-py3.7.egg/locust/main.py", line 53, in __import_locustfile__
    return  source.load_module()
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/scc/software/locust-1.0.3/prometheus_exporter.py", line 94, in <module>
    @web.app.route("/export/prometheus")
AttributeError: module 'locust.web' has no attribute 'app'
```

**运行环境**
 - Locust : 1.0.3
 - OS: Ubuntu 16.04
 - Go Version: 1.13.6

**Comment by myzhan** [comment]
已修复
